site_name: FusOlar Game
site_dir: fusolar
repo-url: https://github.com/Joffrey4/Joffrey4
copyright: Copyright © FusOlar Docs 2016 - All rights reserved.
theme: readthedocs

pages:
    - 'Accueil': 'index.md'